services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - NODE_ENV=production

client:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        - REACT_APP_API_URL=http://server:3000 
    ports:
      - "80:80"
    environment:
      - BACKEND_HOST=server
    depends_on:
      - server